version: 0.2

env:
    variables:
        CACHE_CONTROL: 86400
        S3_BUCKET: $S3_BUCKET_URL
        BUILD_FOLDER: build
phases:
  install:
    runtime-versions:
      nodejs: 12
   
    commands:
        - npm install
       
  build:
    commands:
        - npm run build
     
artifacts:
  files:
    - '**/*'
  base-directory: build